stages:
  - build
  - test

.build_common:
  stage: build
  script:
    - echo "Hello BUILD from ${CC}"
    
build gcc:
  extends: .build_common
  tags:
    - linux
  variables:
    CC: gcc
    
build clang:
  extends: .build_common
  tags:
    - master
  variables:
     CC: clang
    
.test_common:
  stage: test
  script:
    - echo "Hello TEST from ${CI_JOB_NAME}"
    
test gcc:
  extends: .test_common
  tags:
    - linux
    
test clang:
  extends: .test_common
  tags:
    - master