.build_common:
  stage: build
  artifacts:
    paths:
      - build/
  script:
    - mkdir build
    - cd build
    - echo ${CC}
    - echo ${CXX}
    - echo ${PREFIX_PATH}
    - env
    - ${CXX}
    - ninja
    - CC=${CC} CXX=${CXX} cmake ../ -DCMAKE_PREFIX_PATH=${PREFIX_PATH} -G Ninja

    
.build_linux:
  extends: .build_common
  variables:
    PREFIX_PATH: /home/falco/Qt/6.0.2/gcc_64

build gcc:
  extends: .build_linux
  tags:
    - linux
  variables:
    CC: gcc
    CXX: g++
    
build clang:
  extends: .build_linux
  tags:
    - master
  variables:
     CC: clang
     CXX: clang++

build visual-studio:
  extends: .build_common 
  tags:
    - visual-studio
  variables:   
    CC: cl
    CXX: cl
    PREFIX_PATH: C:/Qt/6.0.2/msvc2019_64

.test_common:
  stage: test
  script:
    - build/test/ElysianLuaTests
    
test gcc:
  extends: .test_common
  needs: ["build gcc"]
  dependencies:
    - build gcc
  tags:
    - linux
    
test clang:
  extends: .test_common
  needs: ["build clang"]
  dependencies:
    - build clang
  tags:
    - master
