
stages:
  - build
  - test

build gcc:
  stage: build
  tags:
    - linux
  script: 
    - echo "build GCC!"
    
build clang:
  stage: build
  tags:
    - master
  script:
    - echo "build Clang!"
    
test gcc:
  stage: test
  tags:
    - linux
  script:
    - echo "Test GCC!"
    
test clang:
  stage: test
  tags:
    - linux
  script:
    - echo "Test GCC!"
    